server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 0
      idle-timeout: 600000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    cors:
      mappings:
        "[/**]":
          allowed-origins:
            - "http://localhost:4200"
            # adiciona o domínio do teu frontend em prod, se existir
            # - "https://<o_teu_frontend>.koyeb.app"
          allowed-methods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]
          allowed-headers: "*"
          exposed-headers: ["Location"]
          allow-credentials: true
          max-age: 3600
