server:
  port: ${PORT:8080}

spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    MAIL_FROM_NAME: ${MAIL_FROM_NAME:Barbearia}
    FRONTEND_BASE_URL: ${FRONTEND_BASE_URL:https://barbershop-frontend-nine.vercel.app}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
  MAIL_FROM: ${MAIL_FROM:no-reply@barbearia.example}
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 0
      idle-timeout: 600000
      connection-timeout: 30000
      connection-init-sql: "SET TIME ZONE 'Europe/Lisbon'"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  spring:
    mvc:
      cors:
        mappings:
          "[/**]":
            allowed-origin-patterns:
              - "http://localhost:4200"
              - "https://*.vercel.app"              # cobre previews e o domínio fixo
            allowed-methods: [ GET, POST, PUT, PATCH, DELETE, OPTIONS ]
            allowed-headers: "*"                    # inclui Authorization, Content-Type, etc.
            exposed-headers: [ "Location" ]
            allow-credentials: true                 # se usares cookies/Authorization
            max-age: 3600
