server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update  # (para começar; depois troca por validate + migrações)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
